### PR TITLE
adds support for %config(noreplace) macro

### PR DESCRIPTION
**Pull request by delasky**
This addresses https://github.com/panitw/easy-rpm/issues/58

### CODE REVIEW

**Comment by paulcoyle** [comment]
Thanks for the pull request! Could you please update the tests to reflect these changes?

**Comment by delasky** [comment]
I've added the necessary tests for the %config(noreplace) setting. Thanks!

**Comment by paulcoyle** [comment]
Looks good!  Sorry for the delay in review.

**Comment by delasky** [comment]
@paulcoyle Do you have a target date for the next release that will incorporate these changes?

**Pull request merged**
